# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "ci/requirements/production-requirements.txt", "--without-hashes", "--without-urls", "--without=development" ]
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "ci/requirements/development-requirements.txt", "--without-hashes", "--without-urls", "--with=development" ]
      - id: poetry-install
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: python ./backend/manage.py makemigrations --dry-run --no-input --check
        language: system
        types: [ python ]
        pass_filenames: false
        files: ^backend/
